# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  locationservice:
    image: locationservice
    restart: always
    build:
      context: .
      dockerfile: src/services/LocationService/Dockerfile
    ports:
      - 6001:6001
      - 7001:7001
